<?php

declare(strict_types=1);

namespace Polidog\Relayer\Db;

use Polidog\Relayer\Profiler\Profiler;
use Throwable;

/**
 * Minimal database contract: raw SQL in, plain arrays out.
 *
 * Bound in DI as `Database::class`. The concrete implementation is
 * {@see PdoDatabase}; it is always wrapped by {@see CachingDatabase}
 * (request-scoped memoization) and, in `dev`, additionally by
 * {@see TraceableDatabase} so every query lands in the request
 * {@see Profiler}.
 *
 * Page/component code takes a `Database` dependency and passes SQL with
 * named (`:id`) or positional (`?`) placeholders directly. There is no
 * query builder and no SQL-file loader on purpose — keep it thin; add
 * layers above this contract only when a concrete need appears.
 *
 * {@see insert()} / {@see update()} / {@see delete()} are the one
 * concession: narrow single-table DML sugar so the trivial case isn't
 * hand-written SQL. They build a parameterized statement and route it
 * through `perform()`, so every decorator behavior still applies; the
 * SQL-building lives in {@see PdoDatabase} alone (the decorators just
 * forward, applying their own cross-cutting concern). Anything past the
 * trivial case — JOIN, `OR`, `IN`, expressions, `RETURNING`, upsert,
 * quoted/reserved identifiers — stays raw SQL through `perform()`.
 *
 * Every method either succeeds or throws {@see DatabaseException}; the
 * underlying driver exception is preserved as the previous exception.
 */
interface Database
{
    /**
     * Run a SELECT and return all rows.
     *
     * @param array<int|string, mixed> $params placeholder bindings
     *
     * @return list<array<string, mixed>>
     *
     * @throws DatabaseException
     */
    public function fetchAll(string $sql, array $params = []): array;

    /**
     * Run a SELECT and return the first row, or null when there are none.
     *
     * @param array<int|string, mixed> $params placeholder bindings
     *
     * @return null|array<string, mixed>
     *
     * @throws DatabaseException
     */
    public function fetchOne(string $sql, array $params = []): ?array;

    /**
     * Run a SELECT and return the first column of the first row, or null
     * when there are no rows.
     *
     * @param array<int|string, mixed> $params placeholder bindings
     *
     * @throws DatabaseException
     */
    public function fetchValue(string $sql, array $params = []): mixed;

    /**
     * Run a write statement (INSERT/UPDATE/DELETE/DDL) and return the
     * number of affected rows.
     *
     * @param array<int|string, mixed> $params placeholder bindings
     *
     * @throws DatabaseException
     */
    public function perform(string $sql, array $params = []): int;

    /**
     * INSERT one row into `$table`; return {@see lastInsertId()} (empty
     * string when the driver/table has none).
     *
     * Sugar over `perform()` for the trivial case. Identifiers must be
     * plain (`^[A-Za-z_][A-Za-z0-9_]*$`, `$table` optionally
     * `schema.table`); values are always bound. Quoting, expressions,
     * `RETURNING` or upsert belong in `perform()`.
     *
     * @param array<string, mixed> $data column => value (must be non-empty)
     *
     * @throws DatabaseException on a driver failure, an invalid
     *                           identifier, or empty `$data`
     */
    public function insert(string $table, array $data): string;

    /**
     * UPDATE rows of `$table` matching `$where`; return affected rows.
     *
     * `$where` is equality-only and `AND`-combined; a `null` value
     * becomes `IS NULL`. It must be non-empty — an unfiltered UPDATE
     * (every row) must be written explicitly via `perform()`.
     *
     * @param array<string, mixed> $set   column => new value (non-empty)
     * @param array<string, mixed> $where column => value (non-empty)
     *
     * @throws DatabaseException on a driver failure, an invalid
     *                           identifier, or empty `$set`/`$where`
     */
    public function update(string $table, array $set, array $where): int;

    /**
     * DELETE rows of `$table` matching `$where`; return affected rows.
     *
     * Same `$where` rules as {@see update()}; non-empty is required so a
     * full-table delete goes through `perform()` explicitly.
     *
     * @param array<string, mixed> $where column => value (non-empty)
     *
     * @throws DatabaseException on a driver failure, an invalid
     *                           identifier, or empty `$where`
     */
    public function delete(string $table, array $where): int;

    /**
     * ID generated by the most recent INSERT on this connection. Empty
     * string when the driver has none. `$name` is the sequence name for
     * drivers that need it (e.g. PostgreSQL).
     *
     * @throws DatabaseException
     */
    public function lastInsertId(?string $name = null): string;

    /**
     * Run `$callback` inside a transaction. Commits when it returns,
     * rolls back when it throws. The callback receives a `Database` to
     * issue its statements through — use that argument so the calls stay
     * traced/cached by the surrounding decorators.
     *
     * Whatever the callback throws propagates after rollback: a driver
     * failure surfaces as {@see DatabaseException}, but a domain exception
     * the callback raised itself (e.g. a validation `RuntimeException`)
     * propagates unchanged. So callers must be ready for any `Throwable`
     * from the callback, not only `DatabaseException`.
     *
     * @template T
     *
     * @param callable(Database): T $callback
     *
     * @return T
     *
     * @throws DatabaseException if the transaction or a driver call fails
     * @throws Throwable         whatever `$callback` itself throws
     */
    public function transactional(callable $callback): mixed;
}
