<?php

declare(strict_types=1);

namespace Polidog\Relayer\Db;

use Polidog\Relayer\Profiler\Profiler;

/**
 * Minimal database contract: raw SQL in, plain arrays out.
 *
 * Bound in DI as `Database::class`. The concrete implementation is
 * {@see PdoDatabase}; it is always wrapped by {@see CachingDatabase}
 * (request-scoped memoization) and, in `dev`, additionally by
 * {@see TraceableDatabase} so every query lands in the request
 * {@see Profiler}.
 *
 * Page/component code takes a `Database` dependency and passes SQL with
 * named (`:id`) or positional (`?`) placeholders directly. There is no
 * query builder and no SQL-file loader on purpose — keep it thin; add
 * layers above this contract only when a concrete need appears.
 *
 * Every method either succeeds or throws {@see DatabaseException}; the
 * underlying driver exception is preserved as the previous exception.
 */
interface Database
{
    /**
     * Run a SELECT and return all rows.
     *
     * @param array<int|string, mixed> $params placeholder bindings
     *
     * @return list<array<string, mixed>>
     *
     * @throws DatabaseException
     */
    public function fetchAll(string $sql, array $params = []): array;

    /**
     * Run a SELECT and return the first row, or null when there are none.
     *
     * @param array<int|string, mixed> $params placeholder bindings
     *
     * @return null|array<string, mixed>
     *
     * @throws DatabaseException
     */
    public function fetchOne(string $sql, array $params = []): ?array;

    /**
     * Run a SELECT and return the first column of the first row, or null
     * when there are no rows.
     *
     * @param array<int|string, mixed> $params placeholder bindings
     *
     * @throws DatabaseException
     */
    public function fetchValue(string $sql, array $params = []): mixed;

    /**
     * Run a write statement (INSERT/UPDATE/DELETE/DDL) and return the
     * number of affected rows.
     *
     * @param array<int|string, mixed> $params placeholder bindings
     *
     * @throws DatabaseException
     */
    public function perform(string $sql, array $params = []): int;

    /**
     * ID generated by the most recent INSERT on this connection. Empty
     * string when the driver has none. `$name` is the sequence name for
     * drivers that need it (e.g. PostgreSQL).
     *
     * @throws DatabaseException
     */
    public function lastInsertId(?string $name = null): string;

    /**
     * Run `$callback` inside a transaction. Commits when it returns,
     * rolls back and rethrows when it throws. The callback receives a
     * `Database` to issue its statements through — use that argument so
     * the calls stay traced/cached by the surrounding decorators.
     *
     * @template T
     *
     * @param callable(Database): T $callback
     *
     * @return T
     *
     * @throws DatabaseException
     */
    public function transactional(callable $callback): mixed;
}
