<?php

declare(strict_types=1);

namespace Polidog\Relayer\Router\Routing;

use Polidog\Relayer\Relayer;
use RuntimeException;

/**
 * The compiled-routes artifact: a readable PHP snapshot of everything
 * {@see PageScanner} discovers, so production reads a single OPcache-warm
 * file instead of walking `src/Pages/` on every request.
 *
 * It is a *compile*, not an opaque cache: `export()` emits short-array
 * syntax you can open, diff and reason about, and page/layout paths are
 * stored relative to the app directory so the file is portable across
 * build and deploy environments (and reads as `(marketing)/page.php`
 * rather than a machine-specific absolute path).
 *
 * Presence is the only gate — if the file exists the router loads it,
 * otherwise it scans live. Regenerate with `relayer routes:compile`.
 */
final class CompiledRoutes
{
    private const HEADER = <<<'TXT'
        <?php

        /**
         * AUTO-GENERATED by `relayer routes:compile`. DO NOT EDIT BY HAND.
         *
         * A precompiled snapshot of the routes under src/Pages/. Production
         * reads this instead of walking the filesystem per request; remove
         * it (or just don't compile) and the router falls back to a live
         * scan. Regenerate after changing pages or layouts:
         *
         *     vendor/bin/relayer routes:compile
         *
         * Paths are relative to src/Pages/ so the artifact is portable.
         */

        declare(strict_types=1);

        return
        TXT;

    public static function export(RouteCollection $routes, string $appDir): string
    {
        $appDir = \rtrim($appDir, '/');

        $entries = [];
        foreach ($routes as $route) {
            $entries[] = [
                'pattern' => $route->pattern,
                'regex' => $route->regex,
                'pagePath' => self::relativize($appDir, $route->pagePath),
                'layoutPaths' => \array_map(
                    static fn (string $path): string => self::relativize($appDir, $path),
                    $route->layoutPaths,
                ),
                'paramNames' => $route->paramNames,
                'staticSegments' => $route->staticSegments,
                'totalSegments' => $route->totalSegments,
                'isApi' => $route->isApi,
            ];
        }

        return self::HEADER . ' ' . self::dump($entries, 0) . ";\n";
    }

    /**
     * Write the artifact for `$routes` to `$outFile`, creating the
     * directory when needed.
     *
     * The write is atomic (temp file in the same directory + rename) so a
     * reader can never `require` a half-written artifact — that matters
     * for the runtime warm-up path ({@see Relayer::boot()}
     * with `RELAYER_WARM_CACHE`), where several threads may race to
     * produce the same file while others are serving requests.
     *
     * Returns false on any I/O failure instead of throwing: the CLI turns
     * that into a reported error, the warm-up path degrades to a live
     * scan.
     */
    public static function write(RouteCollection $routes, string $appDir, string $outFile): bool
    {
        $outDir = \dirname($outFile);

        if (!\is_dir($outDir) && !@\mkdir($outDir, 0o775, true) && !\is_dir($outDir)) {
            return false;
        }

        $tmp = $outFile . '.tmp-' . \bin2hex(\random_bytes(4));

        if (false === @\file_put_contents($tmp, self::export($routes, $appDir))) {
            @\unlink($tmp);

            return false;
        }

        if (!@\rename($tmp, $outFile)) {
            @\unlink($tmp);

            return false;
        }

        return true;
    }

    public static function load(string $file, string $appDir): RouteCollection
    {
        $appDir = \rtrim($appDir, '/');

        /** @var mixed $data */
        $data = require $file;

        if (!\is_array($data)) {
            throw new RuntimeException(
                "Compiled routes file {$file} did not return an array. "
                . 'Regenerate it with `relayer routes:compile`.',
            );
        }

        $collection = new RouteCollection();
        foreach ($data as $entry) {
            if (!\is_array($entry)) {
                throw new RuntimeException(
                    "Compiled routes file {$file} is malformed. "
                    . 'Regenerate it with `relayer routes:compile`.',
                );
            }
            $collection->add(self::hydrate($entry, $appDir));
        }

        return $collection;
    }

    /**
     * @param array<mixed, mixed> $entry
     */
    private static function hydrate(array $entry, string $appDir): Route
    {
        return new Route(
            pattern: self::str($entry, 'pattern'),
            regex: self::str($entry, 'regex'),
            pagePath: $appDir . '/' . self::str($entry, 'pagePath'),
            layoutPaths: \array_map(
                static fn (string $path): string => $appDir . '/' . $path,
                self::strList($entry, 'layoutPaths'),
            ),
            paramNames: self::strList($entry, 'paramNames'),
            staticSegments: self::int($entry, 'staticSegments'),
            totalSegments: self::int($entry, 'totalSegments'),
            isApi: self::bool($entry, 'isApi'),
        );
    }

    /**
     * The accessors below narrow values read back from the artifact (all
     * `mixed` as far as the type system knows) and fail loudly on a shape
     * mismatch — a corrupt or hand-edited file should error clearly, not
     * coerce silently.
     *
     * @param array<mixed, mixed> $entry
     */
    private static function str(array $entry, string $key): string
    {
        $value = $entry[$key] ?? null;
        if (!\is_string($value)) {
            throw self::malformed($key, 'string');
        }

        return $value;
    }

    /**
     * @param array<mixed, mixed> $entry
     */
    private static function int(array $entry, string $key): int
    {
        $value = $entry[$key] ?? null;
        if (!\is_int($value)) {
            throw self::malformed($key, 'int');
        }

        return $value;
    }

    /**
     * @param array<mixed, mixed> $entry
     */
    private static function bool(array $entry, string $key): bool
    {
        $value = $entry[$key] ?? null;
        if (!\is_bool($value)) {
            throw self::malformed($key, 'bool');
        }

        return $value;
    }

    /**
     * @param array<mixed, mixed> $entry
     *
     * @return list<string>
     */
    private static function strList(array $entry, string $key): array
    {
        $value = $entry[$key] ?? null;
        if (!\is_array($value)) {
            throw self::malformed($key, 'array');
        }

        $list = [];
        foreach ($value as $item) {
            if (!\is_string($item)) {
                throw self::malformed($key, 'list of strings');
            }
            $list[] = $item;
        }

        return $list;
    }

    private static function malformed(string $key, string $expected): RuntimeException
    {
        return new RuntimeException(\sprintf(
            'Compiled routes artifact is malformed: "%s" must be %s. '
            . 'Regenerate it with `relayer routes:compile`.',
            $key,
            $expected,
        ));
    }

    private static function relativize(string $appDir, string $path): string
    {
        $prefix = $appDir . '/';

        return \str_starts_with($path, $prefix) ? \substr($path, \strlen($prefix)) : $path;
    }

    /**
     * Pretty-print a scalar/array tree as short-array PHP. Leaves go
     * through var_export (correct string escaping); only the array
     * scaffolding is hand-formatted so the artifact stays readable.
     */
    private static function dump(mixed $value, int $indent): string
    {
        if (!\is_array($value)) {
            return \var_export($value, true);
        }

        if ([] === $value) {
            return '[]';
        }

        $isList = \array_is_list($value);
        $inner = \str_repeat('    ', $indent + 1);

        $lines = [];
        foreach ($value as $key => $item) {
            $prefix = $isList ? '' : \var_export($key, true) . ' => ';
            $lines[] = $inner . $prefix . self::dump($item, $indent + 1) . ',';
        }

        return "[\n" . \implode("\n", $lines) . "\n" . \str_repeat('    ', $indent) . ']';
    }
}
